{% set name = "palmerpenguins" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/palmerpenguins-{{ version }}.tar.gz
  sha256: d04d9064930e053fb0805261fe2aa26b4581fdabacaa54d393ddd65bb93bbaf2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - numpy

test:
  imports:
    - palmerpenguins
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mcnakhaee/palmerpenguins
  summary: A python package for the palmer penguins dataset
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
